### PR TITLE
RequestAssetTable

### PR DESCRIPTION
**Pull request by SelcukEdma**
Here is the RequestAssetsTable Component. I used the table `ViewRequests` and pass different props
Here is the catch I passes some extra props to get it work both component. 
Screen Shot 2019-12-13 at 12 04 21 PM

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
JFYI seems like the screenshot you provided doesn't match the data that is being presented in the design documentation. 

https://www.figma.com/file/JRTYL35e6a27C3PaP3h4xp/Kirby-UI-v2.0?node-id=883%3A16774

**Comment by SelcukEdma** [comment]
> JFYI seems like the screenshot you provided doesn't match the data that is being presented in the design documentation.
> 
> https://www.figma.com/file/JRTYL35e6a27C3PaP3h4xp/Kirby-UI-v2.0?node-id=883%3A16774

I was confused by Kirby Design Spec. file. But I remove the domain section now.

**Review by robertwollny-pnmac — COMMENTED** [review]
This looks really good just two minor changes. The sidebar should go to the top of the page. And there are two missing buttons at the bottom of the page
https://drive.google.com/open?id=19STOCgneBO-OMqLPLPDPxcTt2mamn8q8
https://drive.google.com/open?id=1cqjJiXVrC4_VFLN69pk2QMssRM2CnHWC
I don't think the buttons need to work for this MR.

**Review by Jake-Lindvall — COMMENTED** [review]
Awesome job, will agree with Abby and Robert on those details, otherwise 💯

**Comment by SelcukEdma** [comment]
> This looks really good just two minor changes. The sidebar should go to the top of the page. And there are two missing buttons at the bottom of the page
> https://drive.google.com/open?id=19STOCgneBO-OMqLPLPDPxcTt2mamn8q8
> https://drive.google.com/open?id=1cqjJiXVrC4_VFLN69pk2QMssRM2CnHWC
> I don't think the buttons need to work for this MR.

Buttons are in different MR. But I will be making sidebar to top of the page.

**Review by robertwollny-pnmac — APPROVED** [review]
You did a really good job on this 🔥

**Pull request merged**
