### PR TITLE
Kirby Config

### PR DESCRIPTION
**Pull request by robertwollny-pnmac**
You can import the kirbyConfig into any file and you should have access to the correct kirbyConfig object and apiURL based on the hostname. @abbyjb  I added `oldApiUrl` in the localhost and dev so you can still use the old one for the Auth.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
LGTM! though, I would want to verify that the litterbox (LTR) config is the exact same as the offline config from the old kirbyConfig.

**Comment by robertwollny-pnmac** [comment]
> LGTM! though, I would want to verify that the litterbox (LTR) config is the exact same as the offline config from the old kirbyConfig.

As far as I can tell if you go to litterbox you get redirected to localhost so I removed litter box. Let me know if I need to add it back.

**Comment by ghost** [comment]
> > LGTM! though, I would want to verify that the litterbox (LTR) config is the exact same as the offline config from the old kirbyConfig.
> 
> As far as I can tell if you go to litterbox you get redirected to localhost so I removed litter box. Let me know if I need to add it back.

do you have that chrome extension enabled? that's what is redirecting it to localhost. I would add it in

**Comment by robertwollny-pnmac** [comment]
> > > LGTM! though, I would want to verify that the litterbox (LTR) config is the exact same as the offline config from the old kirbyConfig.
> > 
> > 
> > As far as I can tell if you go to litterbox you get redirected to localhost so I removed litter box. Let me know if I need to add it back.
> 
> do you have that chrome extension enabled? that's what is redirecting it to localhost. I would add it in
Ok I thought that was Jon doing that. I will add that back. 🙈

**Review by ghost — APPROVED** [review]

**Review by Jake-Lindvall — APPROVED** [review]
💯

**Pull request merged**
